// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { demos as dm0, frontmatter as fm0, toc as toc0, texts as txt0 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/geometry/path-and-line.en.md?type=meta';
import { demos as dm1, frontmatter as fm1, toc as toc1, texts as txt1 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/geometry/path-and-line.zh.md?type=meta';
import { demos as dm2, frontmatter as fm2, toc as toc2, texts as txt2 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/grammar-of-graphics.en.md?type=meta';
import { demos as dm3, frontmatter as fm3, toc as toc3, texts as txt3 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/grammar-of-graphics.zh.md?type=meta';
import { demos as dm4, frontmatter as fm4, toc as toc4, texts as txt4 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/api/advanced/register-interaction.en.md?type=meta';
import { demos as dm5, frontmatter as fm5, toc as toc5, texts as txt5 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/api/advanced/register-interaction.zh.md?type=meta';
import { demos as dm6, frontmatter as fm6, toc as toc6, texts as txt6 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/geometry/interval.en.md?type=meta';
import { demos as dm7, frontmatter as fm7, toc as toc7, texts as txt7 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/geometry/interval.zh.md?type=meta';
import { demos as dm8, frontmatter as fm8, toc as toc8, texts as txt8 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/geometry/overview.en.md?type=meta';
import { demos as dm9, frontmatter as fm9, toc as toc9, texts as txt9 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/geometry/overview.zh.md?type=meta';
import { demos as dm10, frontmatter as fm10, toc as toc10, texts as txt10 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/geometry/polygon.en.md?type=meta';
import { demos as dm11, frontmatter as fm11, toc as toc11, texts as txt11 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/geometry/polygon.zh.md?type=meta';
import { demos as dm12, frontmatter as fm12, toc as toc12, texts as txt12 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/api/advanced/register-animation.en.md?type=meta';
import { demos as dm13, frontmatter as fm13, toc as toc13, texts as txt13 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/api/advanced/register-animation.zh.md?type=meta';
import { demos as dm14, frontmatter as fm14, toc as toc14, texts as txt14 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/geometry/schema.en.md?type=meta';
import { demos as dm15, frontmatter as fm15, toc as toc15, texts as txt15 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/geometry/schema.zh.md?type=meta';
import { demos as dm16, frontmatter as fm16, toc as toc16, texts as txt16 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/geometry/point.en.md?type=meta';
import { demos as dm17, frontmatter as fm17, toc as toc17, texts as txt17 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/geometry/point.zh.md?type=meta';
import { demos as dm18, frontmatter as fm18, toc as toc18, texts as txt18 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/geometry/area.en.md?type=meta';
import { demos as dm19, frontmatter as fm19, toc as toc19, texts as txt19 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/geometry/area.zh.md?type=meta';
import { demos as dm20, frontmatter as fm20, toc as toc20, texts as txt20 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/api/advanced/dive-into-theme.en.md?type=meta';
import { demos as dm21, frontmatter as fm21, toc as toc21, texts as txt21 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/api/advanced/dive-into-theme.zh.md?type=meta';
import { demos as dm22, frontmatter as fm22, toc as toc22, texts as txt22 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/api/advanced/register-facet.en.md?type=meta';
import { demos as dm23, frontmatter as fm23, toc as toc23, texts as txt23 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/api/advanced/register-facet.zh.md?type=meta';
import { demos as dm24, frontmatter as fm24, toc as toc24, texts as txt24 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/api/advanced/register-label.en.md?type=meta';
import { demos as dm25, frontmatter as fm25, toc as toc25, texts as txt25 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/api/advanced/register-label.zh.md?type=meta';
import { demos as dm26, frontmatter as fm26, toc as toc26, texts as txt26 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/api/advanced/register-shape.en.md?type=meta';
import { demos as dm27, frontmatter as fm27, toc as toc27, texts as txt27 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/api/advanced/register-shape.zh.md?type=meta';
import { demos as dm28, frontmatter as fm28, toc as toc28, texts as txt28 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/api/advanced/register-theme.en.md?type=meta';
import { demos as dm29, frontmatter as fm29, toc as toc29, texts as txt29 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/api/advanced/register-theme.zh.md?type=meta';
import { demos as dm30, frontmatter as fm30, toc as toc30, texts as txt30 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/interaction.en.md?type=meta';
import { demos as dm31, frontmatter as fm31, toc as toc31, texts as txt31 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/interaction.zh.md?type=meta';
import { demos as dm32, frontmatter as fm32, toc as toc32, texts as txt32 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/coordinate.en.md?type=meta';
import { demos as dm33, frontmatter as fm33, toc as toc33, texts as txt33 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/coordinate.zh.md?type=meta';
import { demos as dm34, frontmatter as fm34, toc as toc34, texts as txt34 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/element.en.md?type=meta';
import { demos as dm35, frontmatter as fm35, toc as toc35, texts as txt35 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/element.zh.md?type=meta';
import { demos as dm36, frontmatter as fm36, toc as toc36, texts as txt36 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/adjust.en.md?type=meta';
import { demos as dm37, frontmatter as fm37, toc as toc37, texts as txt37 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/adjust.zh.md?type=meta';
import { demos as dm38, frontmatter as fm38, toc as toc38, texts as txt38 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/api/shape/shape-attrs.en.md?type=meta';
import { demos as dm39, frontmatter as fm39, toc as toc39, texts as txt39 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/api/shape/shape-attrs.zh.md?type=meta';
import { demos as dm40, frontmatter as fm40, toc as toc40, texts as txt40 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/api/advanced/gesture.en.md?type=meta';
import { demos as dm41, frontmatter as fm41, toc as toc41, texts as txt41 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/api/advanced/gesture.zh.md?type=meta';
import { demos as dm42, frontmatter as fm42, toc as toc42, texts as txt42 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/api/advanced/require.en.md?type=meta';
import { demos as dm43, frontmatter as fm43, toc as toc43, texts as txt43 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/api/advanced/require.zh.md?type=meta';
import { demos as dm44, frontmatter as fm44, toc as toc44, texts as txt44 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/view.en.md?type=meta';
import { demos as dm45, frontmatter as fm45, toc as toc45, texts as txt45 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/concepts/view.zh.md?type=meta';
import { demos as dm46, frontmatter as fm46, toc as toc46, texts as txt46 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/example/docs/manual/manual.md?type=meta';
import { demos as dm47, frontmatter as fm47, toc as toc47, texts as txt47 } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/src/pages/Examples/index.tsx?type=meta';

export { components } from './atoms';
export { tabs } from './tabs';

export const filesMeta = {
  'docs/manual/concepts/geometry/path-and-line.en': {
    frontmatter: fm0,
    toc: toc0,
    texts: txt0,
    demos: dm0,
  },
  'docs/manual/concepts/geometry/path-and-line.zh': {
    frontmatter: fm1,
    toc: toc1,
    texts: txt1,
    demos: dm1,
  },
  'docs/manual/concepts/grammar-of-graphics.en': {
    frontmatter: fm2,
    toc: toc2,
    texts: txt2,
    demos: dm2,
  },
  'docs/manual/concepts/grammar-of-graphics.zh': {
    frontmatter: fm3,
    toc: toc3,
    texts: txt3,
    demos: dm3,
  },
  'docs/api/advanced/register-interaction.en': {
    frontmatter: fm4,
    toc: toc4,
    texts: txt4,
    demos: dm4,
  },
  'docs/api/advanced/register-interaction.zh': {
    frontmatter: fm5,
    toc: toc5,
    texts: txt5,
    demos: dm5,
  },
  'docs/manual/concepts/geometry/interval.en': {
    frontmatter: fm6,
    toc: toc6,
    texts: txt6,
    demos: dm6,
  },
  'docs/manual/concepts/geometry/interval.zh': {
    frontmatter: fm7,
    toc: toc7,
    texts: txt7,
    demos: dm7,
  },
  'docs/manual/concepts/geometry/overview.en': {
    frontmatter: fm8,
    toc: toc8,
    texts: txt8,
    demos: dm8,
  },
  'docs/manual/concepts/geometry/overview.zh': {
    frontmatter: fm9,
    toc: toc9,
    texts: txt9,
    demos: dm9,
  },
  'docs/manual/concepts/geometry/polygon.en': {
    frontmatter: fm10,
    toc: toc10,
    texts: txt10,
    demos: dm10,
  },
  'docs/manual/concepts/geometry/polygon.zh': {
    frontmatter: fm11,
    toc: toc11,
    texts: txt11,
    demos: dm11,
  },
  'docs/api/advanced/register-animation.en': {
    frontmatter: fm12,
    toc: toc12,
    texts: txt12,
    demos: dm12,
  },
  'docs/api/advanced/register-animation.zh': {
    frontmatter: fm13,
    toc: toc13,
    texts: txt13,
    demos: dm13,
  },
  'docs/manual/concepts/geometry/schema.en': {
    frontmatter: fm14,
    toc: toc14,
    texts: txt14,
    demos: dm14,
  },
  'docs/manual/concepts/geometry/schema.zh': {
    frontmatter: fm15,
    toc: toc15,
    texts: txt15,
    demos: dm15,
  },
  'docs/manual/concepts/geometry/point.en': {
    frontmatter: fm16,
    toc: toc16,
    texts: txt16,
    demos: dm16,
  },
  'docs/manual/concepts/geometry/point.zh': {
    frontmatter: fm17,
    toc: toc17,
    texts: txt17,
    demos: dm17,
  },
  'docs/manual/concepts/geometry/area.en': {
    frontmatter: fm18,
    toc: toc18,
    texts: txt18,
    demos: dm18,
  },
  'docs/manual/concepts/geometry/area.zh': {
    frontmatter: fm19,
    toc: toc19,
    texts: txt19,
    demos: dm19,
  },
  'docs/api/advanced/dive-into-theme.en': {
    frontmatter: fm20,
    toc: toc20,
    texts: txt20,
    demos: dm20,
  },
  'docs/api/advanced/dive-into-theme.zh': {
    frontmatter: fm21,
    toc: toc21,
    texts: txt21,
    demos: dm21,
  },
  'docs/api/advanced/register-facet.en': {
    frontmatter: fm22,
    toc: toc22,
    texts: txt22,
    demos: dm22,
  },
  'docs/api/advanced/register-facet.zh': {
    frontmatter: fm23,
    toc: toc23,
    texts: txt23,
    demos: dm23,
  },
  'docs/api/advanced/register-label.en': {
    frontmatter: fm24,
    toc: toc24,
    texts: txt24,
    demos: dm24,
  },
  'docs/api/advanced/register-label.zh': {
    frontmatter: fm25,
    toc: toc25,
    texts: txt25,
    demos: dm25,
  },
  'docs/api/advanced/register-shape.en': {
    frontmatter: fm26,
    toc: toc26,
    texts: txt26,
    demos: dm26,
  },
  'docs/api/advanced/register-shape.zh': {
    frontmatter: fm27,
    toc: toc27,
    texts: txt27,
    demos: dm27,
  },
  'docs/api/advanced/register-theme.en': {
    frontmatter: fm28,
    toc: toc28,
    texts: txt28,
    demos: dm28,
  },
  'docs/api/advanced/register-theme.zh': {
    frontmatter: fm29,
    toc: toc29,
    texts: txt29,
    demos: dm29,
  },
  'docs/manual/concepts/interaction.en': {
    frontmatter: fm30,
    toc: toc30,
    texts: txt30,
    demos: dm30,
  },
  'docs/manual/concepts/interaction.zh': {
    frontmatter: fm31,
    toc: toc31,
    texts: txt31,
    demos: dm31,
  },
  'docs/manual/concepts/coordinate.en': {
    frontmatter: fm32,
    toc: toc32,
    texts: txt32,
    demos: dm32,
  },
  'docs/manual/concepts/coordinate.zh': {
    frontmatter: fm33,
    toc: toc33,
    texts: txt33,
    demos: dm33,
  },
  'docs/manual/concepts/element.en': {
    frontmatter: fm34,
    toc: toc34,
    texts: txt34,
    demos: dm34,
  },
  'docs/manual/concepts/element.zh': {
    frontmatter: fm35,
    toc: toc35,
    texts: txt35,
    demos: dm35,
  },
  'docs/manual/concepts/adjust.en': {
    frontmatter: fm36,
    toc: toc36,
    texts: txt36,
    demos: dm36,
  },
  'docs/manual/concepts/adjust.zh': {
    frontmatter: fm37,
    toc: toc37,
    texts: txt37,
    demos: dm37,
  },
  'docs/api/shape/shape-attrs.en': {
    frontmatter: fm38,
    toc: toc38,
    texts: txt38,
    demos: dm38,
  },
  'docs/api/shape/shape-attrs.zh': {
    frontmatter: fm39,
    toc: toc39,
    texts: txt39,
    demos: dm39,
  },
  'docs/api/advanced/gesture.en': {
    frontmatter: fm40,
    toc: toc40,
    texts: txt40,
    demos: dm40,
  },
  'docs/api/advanced/gesture.zh': {
    frontmatter: fm41,
    toc: toc41,
    texts: txt41,
    demos: dm41,
  },
  'docs/api/advanced/require.en': {
    frontmatter: fm42,
    toc: toc42,
    texts: txt42,
    demos: dm42,
  },
  'docs/api/advanced/require.zh': {
    frontmatter: fm43,
    toc: toc43,
    texts: txt43,
    demos: dm43,
  },
  'docs/manual/concepts/view.en': {
    frontmatter: fm44,
    toc: toc44,
    texts: txt44,
    demos: dm44,
  },
  'docs/manual/concepts/view.zh': {
    frontmatter: fm45,
    toc: toc45,
    texts: txt45,
    demos: dm45,
  },
  'docs/manual/manual': {
    frontmatter: fm46,
    toc: toc46,
    texts: txt46,
    demos: dm46,
  },
  'dumi-theme-antv-example-list-zh': {
    frontmatter: fm47,
    toc: toc47,
    texts: txt47,
    demos: dm47,
  },
}

// generate demos data in runtime, for reuse route.id to reduce bundle size
export const demos = Object.entries(filesMeta).reduce((acc, [id, meta]) => {
  // append route id to demo
  Object.values(meta.demos).forEach((demo) => {
    demo.routeId = id;
  });
  // merge demos
  Object.assign(acc, meta.demos);

  // remove demos from meta, to avoid deep clone demos in umi routes/children compatible logic
  delete meta.demos;

  return acc;
}, {});
