// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports.ts';
export * from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/node_modules/_dumi@2.0.0-beta.12@dumi/dist/client/theme-api/index.js';
