// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/node_modules/_dumi@2.0.0-beta.12@dumi/theme-default/slots/Logo/index.js';
export { default } from '/Users/xiaowei/Documents/code/dumi-theme-antv/pkg/node_modules/_dumi@2.0.0-beta.12@dumi/theme-default/slots/Logo/index.js';
