import React, { useState } from 'react';
import styles from '@/.dumi/theme/pages/Examples/index.module.less';
import { Anchor, Menu } from 'antd';
import { debounce } from 'lodash-es';
import { useLocale } from 'dumi';
import { createFromIconfontCN } from '@ant-design/icons';

const MenuIcon = createFromIconfontCN({
  scriptUrl: '//at.alicdn.com/t/font_470089_1lnym745udm.js', // generated by iconfont.cn
});


export interface LeftMenuProps {
  /**
   * 案例主题列表
   */
  exampleTopics: ExamplesPage.ExampleTopic[];
}

/**
 * LeftMenu
 *
 * @param {LeftMenuProps} props 相关参数，详见类型定义
 * @returns {React.FC} React.FC
 * @author YuZhanglong <loveyzl1123@gmail.com>
 */
export const LeftMenu: React.FC<LeftMenuProps> = (props) => {
  const { exampleTopics } = props;

  const [selectedKeys, setSelectedKeys] = useState<string[]>([]);
  const locale = useLocale();
  const [openKeys, setOpenKeys] = useState<string[]>([]);


  const onAnchorLinkChange = debounce((currentActiveLink: string) => {
    // let currentSlug = '';
    // edges.forEach((edge) => {
    //   const {
    //     node: {
    //       frontmatter: { title },
    //       fields: { slug },
    //     },
    //   } = edge;
    //
    //   if (`#category-${title.replace(/\s/g, '')}` === currentActiveLink) {
    //     currentSlug = slug;
    //   }
    // });
    //
    // setSelectedKeys([currentSlug]);
    //
    // if (currentActiveLink) {
    //   const link = document.querySelector(`a[href='${currentActiveLink}']`);
    //   if (link) {
    //     const anchor = link?.parentNode as Element;
    //     anchor.scrollIntoView({
    //       block: 'center',
    //     });
    //   }
    // }
  }, 300);

  return (
    <Anchor className={styles.galleryAnchor} onChange={onAnchorLinkChange}>
      <Menu
        mode='inline'
        selectedKeys={selectedKeys}
        style={{ height: '100%' }}
        openKeys={openKeys}
        onOpenChange={(currentOpenKeys) =>
          setOpenKeys(currentOpenKeys as string[])
        }
        forceSubMenuRender
      >
        {exampleTopics.map((topic) => {
          return <Menu.SubMenu key={topic.id} title={
            <div>
              <MenuIcon className={styles.menuIcon} type={`icon-${topic.icon}`} />
              <span>{topic.title[locale.id]}</span>
            </div>
          }>
            {topic.examples.map((example) => {
              return <Menu.Item key={example.id}>
                <Anchor.Link
                  href={`#category-${example.id.replace(/\s/g, '')}`}
                  title={
                    <div>
                      <span>{example.title[locale.id]}</span>
                    </div>
                  }
                />
              </Menu.Item>;
            })}
          </Menu.SubMenu>;
        })}
      </Menu>
    </Anchor>
  );
};
